### ISSUE TITLE
Move to the latest version of elm-css

### ISSUE THREAD

**Issue by eeue56** [eeue56/take-home#11]
Right now I'm using a dump of elm-css from master from before things were rewritten. We want to be on the latest version of elm-css, which should be a simple upgrade. It'll look something like this:
- Update the `elm-css` folder to have the latest dump of non-test stuff from [here](https://github.com/rtfeldman/elm-css)
- Ensure it compiles and fix any compile errors

In theory, it should be a trivial upgrade.

**Comment by halfzebra** [comment]
What reason why you don't want to use elm-css as a package?

**Comment by eeue56** [comment]
It wasn't published at the time :)

**Comment by halfzebra** [comment]
Sorry, I have removed my question by accident.

Using elm-css as a package causes some troubles with module imports, I'll see if I can get to work during next few days.

**Comment by halfzebra** [comment]
I've hit the issue with `elm-css`,  I think it's somehow related to [elm-css#87](https://github.com/rtfeldman/elm-css/issues/87). I'll see if I can fix that.
